// AUTO-GENERATED. Do not edit by hand.
// Generated by scripts/generate-projects.mjs

export type Category = "extensions" | "renovations" | "new-builds";

export type Project = {
  slug: string;
  title: string;
  category: Category;
  categoryLabel: string;
  location: string;
  cover: string;
  images: string[];
};

export const projects: Project[] = [
  {
    "slug": "extensions-project-01",
    "title": "Project 01",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-01/IMG_0490.JPG",
    "images": [
      "/projects/extensions/project-01/IMG_0490.JPG",
      "/projects/extensions/project-01/IMG_0493.JPG",
      "/projects/extensions/project-01/IMG_0494.JPG",
      "/projects/extensions/project-01/IMG_0496.JPG"
    ]
  },
  {
    "slug": "extensions-project-02",
    "title": "Project 02",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-02/IMG_0676.JPG",
    "images": [
      "/projects/extensions/project-02/IMG_0676.JPG",
      "/projects/extensions/project-02/IMG_0677.JPG",
      "/projects/extensions/project-02/IMG_0678.JPG",
      "/projects/extensions/project-02/IMG_0690.JPG",
      "/projects/extensions/project-02/IMG_0698.JPG",
      "/projects/extensions/project-02/IMG_0699.JPG",
      "/projects/extensions/project-02/IMG_0700.JPG",
      "/projects/extensions/project-02/IMG_0708.JPG",
      "/projects/extensions/project-02/IMG_0709.JPG",
      "/projects/extensions/project-02/IMG_0711.JPG"
    ]
  },
  {
    "slug": "extensions-project-03",
    "title": "Project 03",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-03/IMG_0810.JPG",
    "images": [
      "/projects/extensions/project-03/IMG_0810.JPG",
      "/projects/extensions/project-03/IMG_0814.JPG",
      "/projects/extensions/project-03/IMG_0815.JPG"
    ]
  },
  {
    "slug": "extensions-project-04",
    "title": "Project 04",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-04/IMG_0933.JPG",
    "images": [
      "/projects/extensions/project-04/IMG_0933.JPG",
      "/projects/extensions/project-04/IMG_0934.JPG",
      "/projects/extensions/project-04/IMG_0952.JPG",
      "/projects/extensions/project-04/IMG_0964.JPG"
    ]
  },
  {
    "slug": "extensions-project-05",
    "title": "Project 05",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-05/IMG_1153.JPG",
    "images": [
      "/projects/extensions/project-05/IMG_1153.JPG"
    ]
  },
  {
    "slug": "extensions-project-06",
    "title": "Project 06",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-06/IMG_1431.JPG",
    "images": [
      "/projects/extensions/project-06/IMG_1431.JPG"
    ]
  },
  {
    "slug": "extensions-project-07",
    "title": "Project 07",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-07/IMG_1661.JPG",
    "images": [
      "/projects/extensions/project-07/IMG_1661.JPG"
    ]
  },
  {
    "slug": "extensions-project-08",
    "title": "Project 08",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-08/IMG_1848.JPG",
    "images": [
      "/projects/extensions/project-08/IMG_1848.JPG",
      "/projects/extensions/project-08/IMG_1849.JPG",
      "/projects/extensions/project-08/IMG_1850.JPG",
      "/projects/extensions/project-08/IMG_1883.JPG"
    ]
  },
  {
    "slug": "extensions-project-09",
    "title": "Project 09",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-09/IMG_0192.jpg",
    "images": [
      "/projects/extensions/project-09/IMG_0192.jpg"
    ]
  },
  {
    "slug": "extensions-project-10",
    "title": "Project 10",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-10/IMG_1515.PNG",
    "images": [
      "/projects/extensions/project-10/IMG_1515.PNG"
    ]
  },
  {
    "slug": "extensions-project-11",
    "title": "Project 11",
    "category": "extensions",
    "categoryLabel": "Extensions",
    "location": "Hampshire & Surrey",
    "cover": "/projects/extensions/project-11/cover.webp",
    "images": [
      "/projects/extensions/project-11/01.webp",
      "/projects/extensions/project-11/02.webp",
      "/projects/extensions/project-11/03.webp",
      "/projects/extensions/project-11/04.webp",
      "/projects/extensions/project-11/05.webp",
      "/projects/extensions/project-11/06.webp",
      "/projects/extensions/project-11/07.webp",
      "/projects/extensions/project-11/08.webp",
      "/projects/extensions/project-11/cover.webp",
      "/projects/extensions/project-11/IMG_0010.JPG",
      "/projects/extensions/project-11/IMG_0021.JPG"
    ]
  },
  {
    "slug": "renovations-project-01",
    "title": "Project 01",
    "category": "renovations",
    "categoryLabel": "Renovations",
    "location": "Hampshire & Surrey",
    "cover": "/projects/renovations/project-01/IMG_1768.JPG",
    "images": [
      "/projects/renovations/project-01/IMG_1768.JPG",
      "/projects/renovations/project-01/IMG_1794.JPG"
    ]
  },
  {
    "slug": "renovations-project-02",
    "title": "Project 02",
    "category": "renovations",
    "categoryLabel": "Renovations",
    "location": "Hampshire & Surrey",
    "cover": "/projects/renovations/project-02/cover.webp",
    "images": [
      "/projects/renovations/project-02/01.webp",
      "/projects/renovations/project-02/02.webp",
      "/projects/renovations/project-02/03.webp",
      "/projects/renovations/project-02/04.webp",
      "/projects/renovations/project-02/05.webp",
      "/projects/renovations/project-02/06.webp",
      "/projects/renovations/project-02/07.webp",
      "/projects/renovations/project-02/08.webp",
      "/projects/renovations/project-02/09.webp",
      "/projects/renovations/project-02/10.webp",
      "/projects/renovations/project-02/11.webp",
      "/projects/renovations/project-02/12.webp",
      "/projects/renovations/project-02/cover.webp"
    ]
  },
  {
    "slug": "new-builds-project-01",
    "title": "Project 01",
    "category": "new-builds",
    "categoryLabel": "New Builds",
    "location": "Hampshire & Surrey",
    "cover": "/projects/new-builds/project-01/cover.webp",
    "images": [
      "/projects/new-builds/project-01/01.webp",
      "/projects/new-builds/project-01/02.webp",
      "/projects/new-builds/project-01/03.webp",
      "/projects/new-builds/project-01/04.webp",
      "/projects/new-builds/project-01/05.webp",
      "/projects/new-builds/project-01/06.webp",
      "/projects/new-builds/project-01/07.webp",
      "/projects/new-builds/project-01/08.webp",
      "/projects/new-builds/project-01/cover.webp"
    ]
  }
] as const;
